### PR TITLE
Add automatic nightly release

### PR DESCRIPTION
**Pull request by rhynec**
- A nightly build is now compiled after each commit (when possible).
- Build uses GitHub Actions and a re-creation of PSDK3v2 for Linux prepared and compiled by rhynec (me!).

### CODE REVIEW

**Comment by rhynec** [comment]
Note: Feel free to change the release name, prerelease status, etc. I tried to make the script version independent, which is why the packages are re-tagged to " _nightly.pkg" through the rename.sh script. I've tested the script and similar MGZ builds, but perhaps you could give the released pkgs I currently have in my repo before merging.

**Comment by Zarh** [comment]
I wanted to do something like this, but I didn't know how, thank you very much :)

**Comment by rhynec** [comment]
Unfortunately, the first nightly release failed to upload the ManaGunZ package (FileManager was uploaded though). It seems that it was due to an error with GitHub, but maybe it's the action that I'm using for nightly releases that is doing something weird. Do tag me if it uploads keep failing with other commits. Maybe upload the pkg of MGZ that I released in my fork for the time being, so that there is a pre-release/nightly available?

By the way, I can also implement a workflow which builds and uploads an official release when pushing a tag to the repo, so you don't have to compile the binaries in your own machine. Would you want something like that?

**Comment by Zarh** [comment]
It generates the following errors : 

Error: 💥 error: FetchError: request to https://uploads.github.com/repos/Zarh/ManaGunZ/releases/57760146/assets?name=ManaGunZ_nightly.pkg failed, reason: read ECONNRESET
Error: request to https://uploads.github.com/repos/Zarh/ManaGunZ/releases/57760146/assets?name=ManaGunZ_nightly.pkg failed, reason: read ECONNRESET

I'll update myself the "stable" release, I think it's perfect like it is :)

**Pull request merged**
